### ISSUE TITLE
Add table jumpcloud_windows_program

### ISSUE THREAD

**Issue by Subhajit97** [turbot/steampipe-plugin-jumpcloud#12]
**References**
https://docs.jumpcloud.com/api/2.0/index.html#tag/System-Insights/operation/systeminsights_list_programs

**Comment by oaulicino** [comment]
I am not sure if it is just me, but I can't get this to work well. The error is in the image and it only happens when I run this for Windows. It works well for MacOS.
![image](https://user-images.githubusercontent.com/31516700/219465608-f7b531a4-6f73-4a0d-a728-6bb02f2327dc.png)

**Comment by Subhajit97** [comment]
Hi @oaulicino, sorry I'm unable to reproduce this error. Could you please run the following curl command and provide the output? This will give me an idea about the `install_date` that is causing the error.
```
curl --request GET \
  --url 'https://console.jumpcloud.com/api/v2/systeminsights/programs?skip=0&limit=10' \
  --header 'x-api-key: REPLACE_KEY_VALUE' \
  --header 'x-org-id: SOME_STRING_VALUE'
```

**Comment by oaulicino** [comment]
Hey Subhajit, here you go:


[{"name":"IIS Express Application Compatibility Database for
x64","version":"","install_location":"","install_source":"","language":"","publisher":"","uninstall_string":"%windir%\\system32\\sdbinst.exe
-u
\"C:\\WINDOWS\\AppPatch\\CustomSDB\\{08274920-8908-45c2-9258-8ad67ff77b09}.sdb\"","install_date":"","identifying_number":"","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"},{"name":"Python
3.10.5 Executables
(64-bit)","version":"3.10.5150.0","install_location":"","install_source":"C:\\ProgramData\\Package
Cache\\{0FE1250F-6DD6-4948-B211-741B7CDBB335}v3.10.5150.0\\","language":"1033","publisher":"Python
Software Foundation","uninstall_string":"MsiExec.exe
/I{0FE1250F-6DD6-4948-B211-741B7CDBB335}","install_date":"20220725","identifying_number":"{0FE1250F-6DD6-4948-B211-741B7CDBB335}","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"},{"name":"Notepad++
(64-bit
x64)","version":"8.3.3","install_location":"","install_source":"","language":"","publisher":"Notepad++
Team","uninstall_string":"\"C:\\Program
Files\\Notepad++\\uninstall.exe\"","install_date":"","identifying_number":"","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"},{"name":"IIS
10.0
Express","version":"10.0.06027","install_location":"","install_source":"C:\\ProgramData\\Microsoft\\VisualStudio\\Packages\\Microsoft.VisualStudio.IISExpress.Msi,version=17.1.32112.364,chip=x64\\","language":"1033","publisher":"Microsoft
Corporation","uninstall_string":"MsiExec.exe
/X{028D4B22-B70B-447E-9B80-8E3E98CB2667}","install_date":"20220404","identifying_number":"{028D4B22-B70B-447E-9B80-8E3E98CB2667}","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"},{"name":"Microsoft
.NET Runtime - 6.0.5
(x64)","version":"48.23.40665","install_location":"","install_source":"C:\\ProgramData\\Package
Cache\\{089A177D-98AE-4195-A115-D3C45613B875}v48.23.40665\\","language":"1033","publisher":"Microsoft
Corporation","uninstall_string":"MsiExec.exe
/X{089A177D-98AE-4195-A115-D3C45613B875}","install_date":"20220527","identifying_number":"{089A177D-98AE-4195-A115-D3C45613B875}","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"},{"name":"Microsoft
.NET AppHost Pack - 6.0.3
(x64)","version":"48.15.37625","install_location":"","install_source":"C:\\ProgramData\\Microsoft\\VisualStudio\\Packages\\Microsoft.NetCore.AppHostPack.6.0.6.0.3.x64,version=17.1.32228.430,chip=x64\\","language":"1033","publisher":"Microsoft
Corporation","uninstall_string":"MsiExec.exe
/X{0E342FF4-6ED0-4A90-8241-286A8FF6C89B}","install_date":"20220404","identifying_number":"{0E342FF4-6ED0-4A90-8241-286A8FF6C89B}","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"},{"name":"JumpCloud
Remote
Assist","version":"0.19.0","install_location":"","install_source":"","language":"","publisher":"JumpCloud","uninstall_string":"\"C:\\Program
Files\\JumpCloud Remote Assist\\Uninstall JumpCloud Remote Assist.exe\"
/allusers","install_date":"","identifying_number":"","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"},{"name":"HP
Documentation","version":"1.0.0.1","install_location":"","install_source":"","language":"","publisher":"HP
Inc.","uninstall_string":"CMD /C \"C:\\Program
Files\\HP\\Documentation\\Doc_Uninstall.cmd\"","install_date":"","identifying_number":"","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"},{"name":"Microsoft
Visual C++ 2013 x64 Additional Runtime -
12.0.40664","version":"12.0.40664","install_location":"","install_source":"C:\\ProgramData\\Package
Cache\\{010792BA-551A-3AC0-A7EF-0FAB4156C382}v12.0.40664\\packages\\vcRuntimeAdditional_amd64\\","language":"1033","publisher":"Microsoft
Corporation","uninstall_string":"MsiExec.exe
/X{010792BA-551A-3AC0-A7EF-0FAB4156C382}","install_date":"20220202","identifying_number":"{010792BA-551A-3AC0-A7EF-0FAB4156C382}","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"},{"name":"Microsoft
.NET 6.0 Templates 6.0.203
(x64)","version":"24.5.59963","install_location":"","install_source":"C:\\ProgramData\\Package
Cache\\{1266D47E-431A-4C2F-80E6-8AA23286AC23}v24.5.59963\\","language":"1033","publisher":"Microsoft
Corporation","uninstall_string":"MsiExec.exe
/I{1266D47E-431A-4C2F-80E6-8AA23286AC23}","install_date":"20220527","identifying_number":"{1266D47E-431A-4C2F-80E6-8AA23286AC23}","system_id":"61fad67d914bac1b90dbfe92","collection_time":"2023-02-19T15:57:50.532Z"}]
%


Best regards,

Otto Aulicino, C|CISO, CISSP, CISM, CISA, CCSP
Mobile: +1 (647) 971-5445
http://www.linkedin.com/in/ottoaulicino

**Comment by oaulicino** [comment]
and just to make sure you know, when I run the steampipe query, I am
getting different results with each attempt, even if it is a second apart.
It seems unreliable at the moment.
Best regards,

Otto Aulicino, C|CISO, CISSP, CISM, CISA, CCSP
Mobile: +1 (647) 971-5445
http://www.linkedin.com/in/ottoaulicino

**Comment by Subhajit97** [comment]
Thanks, @oaulicino, for the information. I will try to reproduce the error with the above details.
One more question: Is it the same error you get in every attempt?

**Comment by oaulicino** [comment]
Yes, same error, not necessarily the same output of the steampipe query.
For some reason the query will output different values every time.

Best regards,

Otto Aulicino, C|CISO, CISSP, CISM, CISA, CCSP
Mobile: +1 (647) 971-5445
http://www.linkedin.com/in/ottoaulicino

**Comment by Subhajit97** [comment]
Hi @oaulicino, sorry for the inconvenience. The previous `curl` command I shared will return only the first 10 items. I suspect that you have more than 10 programs installed on your device, and some programs might have the `install_date` value in a different format that caused the above error.

Could you please run the below script and share the response? The below script will gather the whole list for you.

```bash
#!/bin/bash

skip="0"
page="1"

while true; do

  # Call the API
  output=$(curl -s -H "x-api-key: REPLACE_KEY_VALUE" -H "x-org-id: SOME_STRING_VALUE" "https://console.jumpcloud.com/api/v2/systeminsights/programs?skip=$skip&limit=10")

  # Return if the API returns empty data
  if [ "$output" == "[]" ]; then
    break
  fi
  
  # Print the output
  echo -e "\nPage >>> ${page}\n"
  echo $output
  
  # Skip the items that are already processed
  skip=$((skip + 10))

  # Increment the page number
  page=$((page+1))
done

```

**Comment by oaulicino** [comment]
There you go.

Best regards,

Otto Aulicino, C|CISO, CISSP, CISM, CISA, CCSP
Mobile: +1 (647) 971-5445
http://www.linkedin.com/in/ottoaulicino

**Comment by Subhajit97** [comment]
Sorry @oaulicino, I think you have missed adding the result in the above thread.

**Comment by oaulicino** [comment]
I was replying directly via email, and attached a file, but it did not go through it seems. Here you go.
[output.txt.zip](https://github.com/turbot/steampipe-plugin-jumpcloud/files/10815591/output.txt.zip)

**Comment by Subhajit97** [comment]
Thanks, @oaulicino, for providing the details. It helps a lot. I have reproduced the error and pushed a fix for it.
Ref: https://github.com/turbot/steampipe-plugin-jumpcloud/pull/21

We will update you once the changes are available.
Thanks again!
