### ISSUE TITLE
jumpcloud_system_insights table

### ISSUE THREAD

**Issue by oaulicino** [turbot/steampipe-plugin-jumpcloud#16]
It would be great to see the System Insights details, instead of simply knowing whether it is enabled or not (which is what is available on JumpCloud_device).
The API 2.0 link here shows various system insights details that can be gathered. I believe most of them are important for many of us:
https://docs.jumpcloud.com/api/2.0/index.html#tag/System-Insights
The ones I am more interested are hardware-related at the moment, such as CPU, Memory and others, but I would think many of these details are equally important on different occasions.

**Comment by Subhajit97** [comment]
Thanks for the feedback, @oaulicino. We will take a deeper look at the API and check the feasibility of adding those details.
