### ISSUE TITLE
Add table jumpcloud_devices

### ISSUE THREAD

**Issue by oaulicino** [turbot/steampipe-plugin-jumpcloud#5]
The idea here is to retrieve device names, operating systems, IP addresses, software inventory and other asset inventory information, but also policies applied, patches applied, device activities (such as changes to it) etc. 
**References**
https://support.jumpcloud.com/s/article/jumpcloud-admin-implementation-guide-2019-08-21-10-36-47
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

**Comment by misraved** [comment]
Welcome to Steampipe @oaulicino and thanks for raising the request for the new table 👍.

I sifted through the API documentation of JumpCloud, however, I could not find anything pertaining to devices.

I did come across a bunch of APIs that enlist different classes of data like [policy groups](https://docs.jumpcloud.com/api/2.0/index.html#tag/Policy-Groups), [OS Lists ](https://docs.jumpcloud.com/api/2.0/index.html#tag/OS-Lists) etc.

Could you please provide a link to the API that we could employ to extract device information?

Thank you once again for adding the details of your requirement 👍 .

**Comment by oaulicino** [comment]
Hi there,

Apologies, I raised the request without actually knowing whether their APIs
would give access to what we would need.

However, I searched quickly and it seems like their v2.0 has system
association lists that could be what we are looking for.

https://docs.jumpcloud.com/api/2.0/index.html#tag/Systems/operation/graph_systemAssociationsList

I did not try that, so I can't be sure, unfortunately.

Best regards,

Otto Aulicino, C|CISO, CISSP, CISM, CISA, CCSP
Mobile: +1 (647) 971-5445
http://www.linkedin.com/in/ottoaulicino

**Comment by misraved** [comment]
Thanks for the quick response @oaulicino 👍.

This link is a great starting point - https://docs.jumpcloud.com/api/2.0/index.html#tag/Systems/operation/graph_systemAssociationsList

We will look to evaluate the scope of new tables that can be added using the mentioned APIs 👍.

**Comment by misraved** [comment]
Hello @oaulicino, the new `jumpcloud` plugin version `v0.1.0` includes the new `jumpcloud_device` table 👍.

Thanks for raising the request and please let us know if the new table caters to your requirement 👍.

Feedbacks are more than welcome 😄.

**Comment by oaulicino** [comment]
That was sooo fast! Let me try!Best Regards,Otto Aulicino - C|CISO, CISSP, CCSP, CISA, CISMhttps://www.linkedin.com/in/ottoaulicinoOn Feb 3, 2023, at 3:17 PM, Ved misra ***@***.***> wrote:﻿
Hello @oaulicino, the new jumpcloud plugin version v0.1.0 includes the new jumpcloud_device table 👍.
Thanks for raising the request and please let us know if the new table caters to your requirement 👍.
Feedbacks are more than welcome 😄.

**Comment by oaulicino** [comment]
It looks good! I’ll check it out in more detail this weekend, but I took a look at it and liked it a lot!Best Regards,Otto Aulicino - C|CISO, CISSP, CCSP, CISA, CISMhttps://www.linkedin.com/in/ottoaulicinoOn Feb 3, 2023, at 3:17 PM, Ved misra ***@***.***> wrote:﻿
Hello @oaulicino, the new jumpcloud plugin version v0.1.0 includes the new jumpcloud_device table 👍.
Thanks for raising the request and please let us know if the new table caters to your requirement 👍.
Feedbacks are more than welcome 😄.

**Comment by oaulicino** [comment]
Something that would help me a lot is tied to the JumpCloud_Device table,
but it is probably a separate table: software inventory.I am not sure where
it would be in their API documentation, but in the GUI I can find as you
can see in the attachment.


Best regards,

Otto Aulicino, C|CISO, CISSP, CISM, CISA, CCSP
Mobile: +1 (647) 971-5445
http://www.linkedin.com/in/ottoaulicino

**Comment by misraved** [comment]
Thanks for the feedback @oaulicino, we will take a deeper look into the `software inventory` section and check the feasibility of adding it in the form of a table 👍.

**Comment by Subhajit97** [comment]
Hi @oaulicino, just by going through the GUI, I came up with the following details that we could potentially add to our plugin.
![Screenshot 2023-02-09 at 8 33 50 PM](https://user-images.githubusercontent.com/38218418/217849884-cad90adb-828b-4115-ae15-d1250858c803.png)

Could you please confirm if this is what you are looking for? Thanks!

**Comment by oaulicino** [comment]
That is exactly it. The one I am really interested in at the moment is the
Applications one, but they are all important and I believe they will come
in handy in the future.

Best regards,

Otto Aulicino, C|CISO, CISSP, CISM, CISA, CCSP
Mobile: +1 (647) 971-5445
http://www.linkedin.com/in/ottoaulicino

**Comment by Subhajit97** [comment]
Hi @oaulicino, Thank you once again for adding details of your requirement. I was going through the API documentation of JumpCloud, and based on the API availability, we have started working on below tables:
- [jumpcloud_macos_app](#10)
- [jumpcloud_linux_package](#11)
- [jumpcloud_windows_program](#12)

Let us know if these tables cater to your requirement. Thanks!

**Comment by oaulicino** [comment]
That's awesome, thanks! I will try this!
Best regards,

Otto Aulicino, C|CISO, CISSP, CISM, CISA, CCSP
Mobile: +1 (647) 971-5445
http://www.linkedin.com/in/ottoaulicino

**Comment by oaulicino** [comment]
Another one that would be great is
https://docs.jumpcloud.com/api/2.0/index.html#tag/System-Insights as it
shows CPU, Memory and some other useful information.
Best regards,

Otto Aulicino, C|CISO, CISSP, CISM, CISA, CCSP
Mobile: +1 (647) 971-5445
http://www.linkedin.com/in/ottoaulicino
